version: '3.2'

services:
  nexus3:
    env_file:
      - .env
    restart: unless-stopped
    image: ${CONTAINER_REGISTRY_URL}/nexus3
    container_name: nexus3
    volumes:
      - "/data/nexus-data:/nexus-data"
  nginx:
    env_file:
      - .env
    restart: unless-stopped
    image: ${CONTAINER_REGISTRY_URL}/nexus3-nginx-proxy
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - "./nginx/etc/conf.d:/etc/nginx/conf.d"
      - "./nginx/etc/nginx.conf:/etc/nginx/nginx.conf"
      - "/var/log/nginx/:/var/log/nginx/"
    ports:
      - "80:80"
      - "443:443"

