version: '3.2'

services:
  nexus3:
    env_file:
      - .env_dev
    restart: unless-stopped
    image: sonatype/nexus3
    container_name: nexus3
    volumes:
      - "./data/nexus-data:/nexus-data"
  nginx:
    env_file:
      - .env_dev
    restart: unless-stopped
    image: nexus3-docker-nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - "./nginx/etc/conf.d:/etc/nginx/conf.d"
      - "./nginx/etc/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/var/log/:/var/log/nginx/"
    ports:
      - "8080:80"
      - "8443:443"